name: Publish Docker
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push Docker Image
      run: |
        REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        docker build . -t ghcr.io/${REPO}/46elks2telegram
        echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        docker push ghcr.io/${REPO}/46elks2telegram
